## Naïve Bayes classification 

## Importing the libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [ ]:
dataset = pd.read_csv('Q2_pitches_train - Copy.csv')
X = dataset.iloc[:,[0,1,2,3,4,5,6,8,9,10,11,12,13]].values 
y = dataset.iloc[:, [7]].values

In [ ]:
print(dataset.isnull().sum())

inning              0
is_bottom           0
balls               0
strikes             0
outs_before         0
is_lhp              0
is_lhb              0
pitch_type          0
bat_score_before    0
field_score         0
basecode_before     0
batterid            0
pitcherid           0
cid                 0
dtype: int64


In [ ]:
from sklearn.preprocessing import LabelEncoder
Ly = LabelEncoder()
y = Ly.fit_transform(y)
y

/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_label.py:251: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([2, 2, 3, ..., 4, 1, 2])

In [ ]:
Ly.classes_

array(['CB', 'CH', 'FF', 'FT', 'SL'], dtype=object)


## Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [ ]:
print(X_train[:10])

[[   9    0    1    1    0    0    0    5    2    0   93 1373 2046]
 [   6    1    0    0    0    0    1   17    4    3  900 1290 2066]
 [   2    1    1    2    1    0    0    0    0    0  157 1020 2050]
 [   6    0    1    1    1    0    1    0    9    0   29 1292 2057]
 [  12    0    3    2    0    0    0    0    0    1  266 1395 2023]
 [   5    0    1    2    0    0    0    0    6    1  267 1813 2037]
 [   4    0    2    1    1    0    0    0    1    0  248 1603 2020]
 [   4    0    2    2    2    0    0    3    5    1  152 1180 2007]
 [   2    1    0    2    0    1    0    0    1    0  415 1306 2094]
 [   7    0    0    0    0    0    1    0    2    0  109 1051 2006]]


In [ ]:
print(y_train[:10])

[4 0 2 2 3 1 1 2 0 4]


In [ ]:
print(X_test[:10])

[[   8    0    0    0    1    0    1    2    3    0   23 1115 2048]
 [   3    0    0    0    2    1    0    1    1    1  586 1323 2034]
 [   7    1    1    2    1    1    0    6    2    0  330 1435 2037]
 [   8    0    2    2    1    0    0    5    2    5  242 1359 2075]
 [   1    0    0    0    0    1    1    0    0    1   87 1368 2047]
 [   1    0    3    1    2    1    0    0    0    0  155 1059 2018]
 [   7    1    0    1    0    0    1   10    9    0  106 1289 2066]
 [   1    0    1    0    0    1    0    0    0    0  122 1407 2024]
 [   9    0    0    0    0    0    1    6    8    0  184 1159 2024]
 [   5    1    1    0    1    1    0    2    0    0    4 1052 2015]]


In [ ]:
print(y_test[:10])

[3 1 0 2 4 2 1 4 3 2]


## Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
print(X_train[:10])

[[ 1.47859979e+00 -9.80015881e-01  1.13739699e-01  1.28060316e-01
  -1.18823181e+00 -6.18603075e-01 -8.39417422e-01  9.43502904e-01
  -1.66603619e-01 -6.09638222e-01 -9.57022464e-01  2.87924892e-01
   3.45012484e-01]
 [ 3.64037521e-01  1.02039163e+00 -9.14181051e-01 -1.07909969e+00
  -1.18823181e+00 -6.18603075e-01  1.19130241e+00  5.36779307e+00
   5.50402825e-01  1.16057779e+00  3.34057221e+00 -1.33848252e-01
   1.11000543e+00]
 [-1.12204550e+00  1.02039163e+00  1.13739699e-01  1.33522032e+00
   3.32421792e-02 -6.18603075e-01 -8.39417422e-01 -8.99951332e-01
  -8.83610064e-01 -6.09638222e-01 -6.16197112e-01 -1.50588137e+00
   4.98011072e-01]
 [ 3.64037521e-01 -9.80015881e-01  1.13739699e-01  1.28060316e-01
   3.32421792e-02 -6.18603075e-01  1.19130241e+00 -8.99951332e-01
   2.34291893e+00 -6.09638222e-01 -1.29784782e+00 -1.23685044e-01
   7.65758603e-01]
 [ 2.59316206e+00 -9.80015881e-01  2.16958120e+00  1.33522032e+00
  -1.18823181e+00 -6.18603075e-01 -8.39417422e-01 -8.99951332e-01


In [ ]:
print(X_test[:10])

[[-1.1220455  -0.98001588  0.1137397  -1.07909969  0.03324218 -0.61860307
  -0.83941742 -0.89995133  0.1918996  -0.60963822  0.84296143  1.54816272
   0.57451037]
 [-0.75052475 -0.98001588 -0.91418105 -1.07909969  1.25471617  1.61654547
  -0.83941742 -0.53126048 -0.16660362 -0.60963822 -0.55761775 -1.18065871
  -1.33797199]
 [-0.00748324  1.02039163  0.1137397   1.33522032 -1.18823181 -0.61860307
  -0.83941742 -0.89995133 -0.88361006 -0.60963822  0.92816777 -1.46014693
  -1.14672376]
 [-1.1220455   1.02039163 -0.91418105  0.12806032 -1.18823181 -0.61860307
  -0.83941742 -0.89995133 -0.88361006  0.57050578  0.20391389  0.28284329
  -0.45823011]
 [-0.37900399  1.02039163 -0.91418105  1.33522032 -1.18823181  1.61654547
   1.19130241 -0.16256964  0.1918996  -0.60963822 -1.05820499 -1.14508748
  -0.49647975]
 [-0.75052475 -0.98001588 -0.91418105  0.12806032  1.25471617 -0.61860307
  -0.83941742 -0.89995133 -0.52510684 -0.01956622 -0.14756225  1.57357074
   1.18650472]
 [ 1.10707903  1.02039

## Training the Naïve Bayes classification  model on the Training set

In [ ]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [ ]:
print(classifier.predict_proba(sc.transform([[40,87000,10]])))

## Predicting the Test set results

In [ ]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[2 3]
 [2 1]
 [2 0]
 ...
 [2 4]
 [2 2]
 [2 3]]


In [ ]:
y_pred1 = classifier.predict_proba(X_test)
print(y_pred1)


[[0.13318714 0.10910625 0.42003122 0.19652171 0.14115368]
 [0.1466111  0.14749478 0.31725017 0.24821153 0.14043242]
 [0.11907431 0.12738624 0.35738668 0.14990756 0.2462452 ]
 ...
 [0.13443293 0.18122524 0.36082518 0.18969696 0.13381968]
 [0.11085397 0.10898902 0.36353092 0.15730498 0.2593211 ]
 [0.12203945 0.08656169 0.38473982 0.23694074 0.1697183 ]]


## Making the Confusion Matrix

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[    0     0 11144     0   764]
 [    0     0 13975     0   670]
 [    0     1 45185     0  2852]
 [    0     0 20506     0  1103]
 [    0     0 21949     0  2080]]


0.39312478686506586